# Generated by Django 4.2 on 2024-01-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_phonecode_reg_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
