# Generated by Django 4.2 on 2024-01-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staffreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffreg',
            old_name='username',
            new_name='city',
        ),
        migrations.AddField(
            model_name='staffreg',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffreg',
            name='pincode',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
