# Generated by Django 4.2 on 2024-01-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_username_staffreg_city_staffreg_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staffreg',
            new_name='stareg',
        ),
    ]
