# Generated by Django 4.2 on 2024-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_staffreg_stareg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stareg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='stareg',
            name='pincode',
        ),
        migrations.AddField(
            model_name='stareg',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
