# Generated by Django 3.0.5 on 2024-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240215_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
