# Generated by Django 3.0.5 on 2024-02-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240217_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
