# Generated by Django 3.0.5 on 2024-02-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assign_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='name',
        ),
    ]
