# Generated by Django 3.0.5 on 2024-02-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
