# Generated by Django 3.0.5 on 2024-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_update_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='fname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
