# Generated by Django 3.0.5 on 2024-02-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_update_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='fname',
        ),
    ]
