# Generated by Django 3.0.5 on 2024-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20240223_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='ward',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
