# Generated by Django 3.0.5 on 2024-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_assign_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='price',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
