# Generated by Django 3.0.5 on 2024-02-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='phonenumber',
        ),
    ]
