# Generated by Django 4.2.11 on 2024-03-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_booking_delete_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='main.reg'),
        ),
    ]
