# Generated by Django 4.2.11 on 2024-03-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_booking_username_booking_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='owner',
        ),
    ]
