# Generated by Django 4.2.11 on 2024-03-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_reg_user_alter_reg_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coordinate',
        ),
    ]
