# Generated by Django 4.2.11 on 2024-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
